name: Hello ISIS3710!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: say hello,
      run: 

          echo "Hello ISIS3710"
      --date: displays date
        run: 

          echo "date"
     